[Add]test of task system
Megumi-N/runteq_rspec_app_exam pull request #1
Opened 2021-01-24 14:07 UTC by noguchime

Rspec編課題4についてpull requestします。
ご確認のほどよろしくお願いします。

2021-01-25 02:52 UTC, yuji91 requested changes
修正はほとんど問題なかったですが、いくつか指摘しました！

2021-01-25 02:52 UTC, yuji91 commented on spec/factories/tasks.rb
> +  trait :task_finished_status do
「ステータスが完了になっていること」以外にも「完了日時が登録されていること」などの要素があるので「finished」などのtrait名の方が分かりやすいかもしれません。

また今回は`done`というステータスがあるので、`finished`よりはステータス名の`done`に合わせた方が良いでしょう。
```suggestion
  trait :done do
```

2021-01-25 02:52 UTC, yuji91 commented on spec/factories/tasks.rb
> +    association :project
associationはこのtraitに限定せず、このFactory全体に適用させて良いと思います。

2021-01-25 02:52 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project: project) }
Factoryの指摘事項を対応することで省略可能です。
```suggestion
  let(:task) { create(:task) }
```

2021-01-25 02:52 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%_m/%d %H:%M'))
NG例のPRを確認して欲しいのですが、この部分を変更するとView側の表示メソッドの仕様変更時にテストが落ちてしまいます。

2021-01-25 02:52 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find '.task_list').not_to have_content task.title #.task_listの中にtask.titleが入ってないことを確認。以下のexpectもこの指定が適応される
修正方法は問題ないですが「以下のexpectもこの指定が適応される」という点はどの事象から判断された形になりますでしょうか？

2021-01-25 05:40 UTC, noguchime commented on spec/system/task_spec.rb
> +        expect(find '.task_list').not_to have_content task.title #.task_listの中にtask.titleが入ってないことを確認。以下のexpectもこの指定が適応される
そのように考えたのですが、質問コーナーで認識違いということがわかりました。
上記のコメントアウトの記載は削除します。

2021-01-26 09:04 UTC, yuji91 approved these changes
修正確認しました。

指摘事項があった際は、指摘内容ごとに修正のコミットを分けられると、確認がしやすくて良いと思います！

2021-10-29 01:37 UTC, merged